adamdruppe/arsd

dom.d

Not sure if this was not added previously for a reason, but adding it was helpful for me.

Trivial change - adding getElementsByClassName to Document

---

minigui.d

Makes it easier to add more backends

Made minigui use version win32_widgets, else custom_widgets else static assert false

---

dom.d

Added euro (€) to entity list

---

dom.d

If you have a `<p>` containing multiple `<p></p>`, we need to add them to their parent in order. This requires tracking what the last thing we moved was so we can insert in the right order.
Addresses #120, at least the test case presented there.

dom.d: Improve handling of mixed <p> tags

---

mysql.d

Added port paramater to mysql

---

nanovega.d
simpledisplay.d

Fix some unreachable statement warnings on dub

Fix warnings in simpledisplay & nanovega blocking dub builds

---

simpledisplay.d

Implement setOpacity on X11

---

simpledisplay.d

part of #141, modified a bit as discussed on IRC and also made the windows implementation get the window length and then allocate depending on it.

Made SimpleWindow.title fetch the actual current title

---

simpledisplay.d
wmutil.d

Contains findWindowByClass and ownerPID for now, planning on adding more window getters (part of #141)

Added new wmutil module

---

terminal.d

remove renaming note

---

cgi.d

Using dmd version 2.080.0, `cgi.d` fails to compile, with errors related to the initialization of immutable fields. This PR fixes those errors by replacing switch statements with if-else chains, as recommended in the [dmd 2.080.0 changelog](https://dlang.org/changelog/2.080.0.html#fix18736).
Fixes #158

cgi: fix build errors with dmd 2.080.0

---

simpledisplay.d

https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glSecondaryColor.xml

Add bindings for glSecondaryColor

---

sqlite.d

SQLite: Fix spelling typo

---

color.d

I have added properties for the other 2 vertexes of the Rectangle, the upperRight and the lowerLeft vertexes.

Adding 2 more properties

---

simpledisplay.d

I am making a program that draws circles and I noticed there were no functions for that but I could make it happen by using drawArc() the right way so I figured it would be a good idea to add a drawCircle() function. This new function was crafted using the preexisting drawArc() function. I have tested it and it is much more practical than using drawArc() when working with pure circles.

Give ScreenPainter another function

---

nanovega.d

- Support for external OpenGL and FreeType bindings
- Modernization of OpenGL calls
- Change of behavior of the mipmapping option (existing code may render differently with this change)
- Addition of a LOD bias for better render quality of textures

Some improvements to nanovega

---

nanovega.d

Last modernization attempt was garbage, so here's something that should work.

Replace broken OpenGL solution with working one

---

terminal.d

Not sure whether this is the right fix for issue #211, but seems to be.

Fix issue 211 (timeout compile error)

---

mysql.d

sysTimeToValue should be in the MySql Class not the MySqlResult class

---

color.d

Now it is working properly, I have implemented it the right way now.

Fixing the .center() property

---

cgi.d

See: https://forum.dlang.org/post/ohvfmvupshlljqewqbmr@forum.dlang.org

Fix unreachable statement on Windows

---

simpledisplay.d

I've updated the definition of the drawCircle() function because the previous definition was not working properly.

Updating the drawCircle() function

---

simpledisplay.d

I've just moved those 2 functions to simpledisplay.

Moving those 2 functions here

---

http2.d

The current `class HttpRequest` does not support timeout configuration: the default timeout for each request is hardcoded to 10 seconds, which can render the client unusable on slow connections. 
The proposed changes allow a timeout to be set on a `HttpRequest` object using the non-empty constructor or by modifying the timeout field directly after a request has been initialized. Example:
```D
import std.stdio;
import core.time;
import arsd.http2;
void main()
{
auto client = new HttpClient();
auto request = client.navigateTo(Uri("http://dlang.org")); // what if dlang.org takes >10 seconds to load...
request.timeout = 20.seconds;
auto response = request.waitForCompletion();
assert(response.wasSuccessful, response.codeText);
writeln(response.contentText);
}
```

Timeout support in HttpRequest

---

cgi.d

Get from https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

add missing http response codes

---

cgi.d

#315 
I've fixed a typo with the code and made it so you don't need a port for unix sockets

Fix unix socket code

---

http2.d

List of domains, ips or ip ranges to not use a proxy with. By default uses the no_proxy or NO_PROXY environment variable.

add support for no_proxy / proxy ignore hosts

---

http2.d

This should fix SSL loading on macOS while allowing for easy additions on so-name bumps on any platform.
Big disclaimer: I don't know enough to know if it's correct, I just know it seems to work. Tested on Manjaro/Arch, Windows 11 and macOS Catalina, all x86_64.
Just close if you'd prefer to write (or have already written) a solution yourself.

Use arrays for potential OpenSSL lib filenames

---

cgi.d
fibersocket.d

Make it compile after https://github.com/dlang/phobos/pull/8438

Add `scope` to Socket derived functions

---

terminal.d

Terminal save & restore cursor

---

jni.d

I guess that code-path had never been visited before 😬

missing std.conv : to import

---

jni.d

This approach should probably be somewhat principled 😛

java translation: more reserved words

---

apng.d
com.d
database.d
engine.d
exception.d
game.d
html.d
htmlwidget.d
http.d
http2.d
jni.d
jsvar.d
minigui.d
minigui_addons/color_dialog.d
mssql.d
mysql.d
oauth.d
png.d
qrcode.d
rss.d
screen.d
script.d
simpleaudio.d
sqlite.d
sslsocket.d
terminal.d
terminalemulator.d
web.d
wmutil.d

last time I forgot to remove tabs 🤦 
``for fn in `git ls-files \*.d`; do sed -i -e's/[ \t]\+$//g' $fn; done``

trailing whitespace

---

minigui.d

Simple function addition so that the CharEvent terminates when the readonly flag is true.

Feature: Readonly support to editable text widgets

---

terminal.d

This avoids including rpc module from windows which takes 200ms to build

Build terminal faster

---

sqlite.d

Sqlite is able to store 64 bit floating-point values, but the arsd.sqlite diver does not support this.
This adds support for values of type double when binding values to a query. Prior to this, doubles would be converted to a string and only be stored with 6 digits of precision in the database.
Additionally, floats stored in the database were converted to strings when retrieved and therefore be reduced to 6 digits of precision, too. This behavior is now fixed for floats and doubles.
---
This unittest checks that doubles now work as expected.
```d
unittest
{
import arsd.database;
import arsd.sqlite;
import std.math : feqrel;
import std.conv : to;
double d = 1.0/3.0;
auto db = new Sqlite(":memory:");
db.query("CREATE TABLE test(d REAL);");
db.query("INSERT INTO test VALUES (?)", d);
auto …
```

sqlite: Improve precision for floating-point types

---

core.d

Use `ArsdUseCustomRuntime` for supporting them.

Added support to wasm and custom runtimes

---

core.d

Do nothing EmptyCoreEvent version added.

iOS compatibility

---

color.d

I’m so sorry for this embarrassing bug :/

Fix ColorF(Color) constructor

---

README.md
dub.json
package.d
pixelpresenter.d
pixmappresenter.d
simpledisplay.d

**Pixel Presenter** is a high-level display library for one specific scenario: Blitting fully-rendered frames to the screen.
This is useful for software-rendered applications. Think of old-skool games, emulators etc.

Add Pixmap Presenter module

---

pixmappresenter.d

How did this even make it past my own QA? :/

Fix OpenGl3PixmapRenderer.reconfigure()

---

nanovega.d

adds documentation how to use them as well

fix nanovega fallback fonts

---

mvd.d

the last unittest seems to trigger an internal compiler error in OpenD, not sure why since OpenD has like no actual changes, but it works on the latest DMD so I imagine it will get fixed automatically if the latest changes are pulled

make mvd work with immutable classes

---

email.d

Quick candidate "fix" for #428 so you can decide whether you like it or if it's too obtrusive/ noisy.
This should also increase the visibility of the issue in case anybody encounters it again

Let user define linesep + documentation

---

com.d

I was using Excel's COM's interface and wanted the result of `xlApp.ActiveWorkbook.ActiveSheet.Evaluate()("=SUM(A1:A2)")`. This adds basic support for retrieving a float / double, probably could implicitly promote float to double but this is a start.

com.d: Support float / double retrieval in Variant

---

README.md
core.d
dub.json
pixmappaint.d
pixmappresenter.d

**Pixmap Paint** is supposed to become a 2D drawing companion library of Pixmap Presenter.
Bonus:
Makes Pixmap manipulation available without the sdpy dependency.

Add Pixmap Paint module

---

com.d

This enables setting a range of cells in Excel like so:
```D
auto range = sheet.Range()(sheet.Cells()(5, 1), sheet.Cells()(9, 5));
string[][] val = [["A", "B", "C"], ["CCC", "D", "E"]];
range.Value() = val;
```

com.d: support (multi-dimensional) array paramters

---

com.d

https://github.com/adamdruppe/arsd/pull/441 follow up

com.d: Fix named arguments count

---

com.d

Makes it easier to improve the message

com.d: deduplicate error handling of `Invoke`

---

README.md
dub.json
pixmaprecorder.d

I’m positively surprised how *simple* it is to create actual video files from frame data.
Let’s make it *easy* as well.

Add Pixmap Recorder module

---

dub.json

Let’s not use trailing commas.

Fix JSON syntax

---

pixmappresenter.d

Fixes a bug that is masked by #459 on many systems.

Fix PixmapPresenter not glClear()'ing as expected

---

pixmappaint.d
pixmappresenter.d

- Adds an upscaler/downscaler implementation.
- Adds fixed-point math type via `UDecimal`.
- Documentation improvements.

PixmapPaint February ’25 update

---

minigui.d

Not very familiar with the code, so there are non-idiomatic stuff here, perhaps.
I'm aware that It'll be nice if the user gets information like balloon popup but don't know for now.

Make buttons disableable for custom drawn buttons

---

ini.d

Fix typos.
Clarify instructions for instantiating a non-destructive parser for mutable data.

Improve documentation of `arsd.ini`
