adamdruppe/arsd

jpeg.d
Fix dmd v2.073.0 compiler errors in jpeg.d due to int to size_t and size_t to int casting
=> Fix compiler errors in jpeg.d

database.d, mssql.d, mysql.d, postgres.d, sqlite.d
Ran into this recently. Phobos is now complaining:
````
/usr/src/d/phobos/std/range/primitives.d(1411): Note: length must have type size_t on all systems, please update your code by December 2017.
````
whenever I use `ResultSet` as a range.
The fix is trivial.
WARNING: I only tested `sqlite.d` for this PR, because that's what I'm currently using. (Thanks, BTW! It's an awesome module, sweet and simple. Just what I need.) But I figured the fix is simple so it shouldn't break anything, so I went ahead and changed it for everything that implements `arsd.Database.ResultSet`. Hope that's OK. If not, I'll be happy to shrink the diff to just `sqlite.d`.
=> Range API needs size_t for .length.

sqlite.d
Basically two main changes:
1. Add a 64-bit overload for `bind()` so that 64-bit values are properly bound by SQLite;
2. When returning a result set, extract `SQLITE_INTEGER` as 64-bit instead of 32-bit, so that 64-bit values are converted correctly. For 32-bit fields, the 64-bit return should just convert back to 32-bit losslessly. Not 100% sure if this will cause code breakage; does `Variant` allow casting a 64-bit boxed value to 32-bit implicitly?
=> [sqlite.d] Fix 64-bit int binding/selecting troubles

minigui.d
Hi Adam,  
Thanks for your Minigui library. It seems, it is the thing I had been desperately searching for years: a really concise library able to produce apps accessible to screen readers (i.e., with native controls on Windows - it is enough for me) and to make automagic layouts.  
I know I'm a bit too nerdy here, but it should be separator, not seperator :).
=> Fixed spelling: It should be separator

png.d
I got an error with `-dip25` so I added `return` (could have it return `auto` to make it inferred if you don't like the noise).
Also took opportunity to not lie about `immutable` and remove some casts.
=> improve png chunk stype

nanovega.d, simpledisplay.d
These flags allow better control of texture outputting for nice visual effects.
=> Additional image flags.

dub.json
A single file library that translates HTML to pain text that is basically markdown ? Please take my money !
`htmltotext.d` can be very useful on its own.
I also added `color_base` as a dependency, as it's used in `htmltotext.d` and is necessary for it to compile.
=> Split email and htmltotext subpackages

nanovega.d
#include and #define made dmd and ldc very unhappy.
Fixes
```
/home/webfreak/.dub/packages/arsd-official-2.1.2/arsd-official/nanovega.d(13215,12): Warning: C preprocessor directive #define is not supported
/home/webfreak/.dub/packages/arsd-official-2.1.2/arsd-official/nanovega.d(13216,12): Warning: C preprocessor directive #define is not supported
/home/webfreak/.dub/packages/arsd-official-2.1.2/arsd-official/nanovega.d(13217,12): Warning: C preprocessor directive #define is not supported
/home/webfreak/.dub/packages/arsd-official-2.1.2/arsd-official/nanovega.d(13218,12): Warning: C preprocessor directive #define is not supported
/home/webfreak/.dub/packages/arsd-official-2.1.2/arsd-official/nanovega.d(13219,12): Warning: C preprocessor directive #define is not supported …
```
=> Fix nanovega compilation warnings

dub.json
By purpose I didn't added the sub packages as dependencies to the root package because this would everyone having a dependency to "arsd-official" forcing to have all the libs of all sub packages.
I think this doesn't makes sense.
=> dub.json changes for database modules

color.d, nanovega.d, png.d
I've run into some integer overflow issues with color.d and png.d when trying to work with images that have slightly bigger dimensions than normal, this PR fixes those issues.
- setPixel doesn't produce bogus array indices for sane input anymore.
- saving and loading big images works now (on 64 bit platforms).
In a basic test using a 30000x20000 RGBA image, the image could be saved correctly and decoded correctly both in it's original encoding and in reencoded (by external tool) form. Before the fix the output file was terminated abruptly and broken.
=> Support big images

dub.json
- Switched to target type "library"
- Removed configurations from "minigui" as it has no effect. The configuration (linker flags + versions) are only relevant for "simpledisplay".
Specifying the configuration would look like this:
```json
{
"name": "minisample",
"dependencies": {
"arsd-official:minigui": {"path": "C:\\Users\\pc\\git\\arsd"},
"arsd-official:simpledisplay": {"path": "C:\\Users\\pc\\git\\arsd"},
},
"subConfigurations": {
"arsd-official:simpledisplay": "without-opengl"
}
}
```
Please note, you can only set a configuration for a dependency which is explicetly mentioned, therefore you have to mention simpledisplay.
=> fix minigui dub config

terminal.d
See issue #209. As it turns out, the problem wasn't 256 color support itself, but the fact that on my Debian box `TERM` is set to `rxvt-unicode-256color`, but `terminal.d` doesn't recognize this particular string.  Not 100% sure this is the right fix, but it did at least display 16-color mode correctly. I'll try a small 256-color test program next.
=> Recognize TERM=rxvt-unicode-256color.

simpledisplay.d
I've made the .clear() method more practical by giving the user the ability to decide which color the screen will be cleared with and setting the default as black since this is what you will probably be using.
=> Setting up the .clear() method better

nanovega.d
NVGImage can be creating using existing OpenGL texture. Currently provided functionality only allows to create GLNVGtexture from existing OpenGL texture id. And there is no way to create NVGImage from GLNVGtexture.
=> Enable using existing OpenGL textures

dom.d
This is similar to #222 except it's triggered when attempting to create a `profile` build. This also introduces a `Deprecation: switch case fallthrough` instead but I'm not sure of the best way to resolve that.
=> Fix unreachable statement

color.d, simpledisplay.d
Trivial fix, just thought I'd help get rid of annoying deprecation messages.
=> Fix deprecation warnings for `body`.

simpledisplay.d
This one had me scratching my head over linker errors, until I figured out it's capital `S` not small `s`. :D
=> Fix typo: `wmainCRTStartup` (capital S) not `wmainCRTstartup`.

database.d, database_generation.d
Using `tupleof` instead of `__traits(allMembers, ...)` skips over all
nested declarations that are not actual fields.
=> database_generation: Don't assign to functions, ... in populateFromDbRow

simpleaudio.d
I have just added .paused() as a property to SampleController because it has .finished(), to tell if it's been stopped, but it has none to tell if it has been paused
=> adding .paused() as a property

dom.d
I added the tags:
`area`, `base`, `param`, `embed`, `track`, and `wbr`
Used the list from here
https://developer.mozilla.org/en-US/docs/Glossary/Empty_element
=> update list of self-closing tags

cgi.d
Moves the previously thread-local uid/guid variables into `RequestServer`.
Checks whether `setgid`/`setuid` succeeds, throws otherwise.
Being uid `0` (aka root) is no longer a precondition – see also: [CAP_SETUID](https://linux.die.net/man/7/capabilities).
Background:
I was particularly unhappy that there was no API to set uid/gid apart from `configureFromCommandLine(string[])`
=> Improve privilege dropping in cgi.d

minigui.d
Idea is, you can store arbitrary data (e.g. a class pointer) with the item. Therefore while reacting on ChangeEvent, you have all needed data.
```d
import arsd.minigui;
class Foo
{
int i;
}
void main()
{
auto window = new MainWindow();
auto list = new ListWidget(window);
Foo foo1 = new Foo();
foo1.i = 3;
list.addOption("Sample", cast(ptrdiff_t) cast(void*) foo1);
Foo foo2 = cast(Foo) cast(void*) list.options[0].tag;
window.loop();
}
```
=> Add list option tag and getSelection

database_generation.d
Use `tableNameFor` which takes into consideration DBName instead of `toTableName`.
=> make children take DBName into consideration

database_generation.d
Handle when "" is passed to t1 or t2.
Currently if "" gets passed to t1 or t2 it will just result in a compilation error. This pr handles that case by not generating the respective function if t1 or t2 is left empty. Example
```d
struct Role { int id; }
struct User {
int id;
@ForeignKey!(Role.id, "") int role_id;
}
mixin(one_to_many(User.role_id, "role", ""));
Database db = ...
User user = ...
Role role = user.get_role(db); / / Works
auto users = role.get_users(db); // Doesn't because t1 is ""
```
=> One to many handle empty str

database_generation.d
Make find be able to take a field name like in the docs. It helps in case searching for a table that has an `id` with a different name, for example in sqlite3 `row_id`.
=> Make find work as advertised

database_generation.d
Basically makes clearer the fact that `find` only works with Integral fields, and makes debugging easier.
P.S. I forgot to add this in the previous pr. Sorry.
=> Add integral field check to find

simpledisplay.d
The latter is not compatible with -preview=in.
=> Use scope const auto ref instead of in auto ref

minigui.d
When you use the addtext method on the TextEdit class, the scrollbar does not recalculate its size properly.  
This is a simple fix. 
Preview of the error in action
Preview of the fix in action
=> bugfix: scrollbar wasn't updating on addtext calls

cgi.d
cgi.d currently manually casts socklen_t to int on android. Currently, the [current commit in druntime] (https://github.com/dlang/dmd/blob/1188adc84ff1777f4a0153a8a5d7729ab5866dce/druntime/src/core/sys/posix/sys/socket.d)  aliases socklen_t as uint, I can't find an exception for android or ARM.
To stay more robust to further changes in the druntime core library, I suggest just using socklen_t directly. I tested this on android 13 (termux) and linux.
=> Use the alias socklen_t for portability

simpleaudio.d
Winapi requires the nBlockAlign to be channels times bytes per sampe, otherwise errors out
=> Fix WAVERR_BADFORMAT in simpleaudio.d

color.d
Adds floating-point color representation wrapper struct (with contracts) to `arsd.color`.
```d
auto clear = ColorF(backgroundColor);
glClearColor(clear.r, clear.g, clear.b, clear.a);
```
Correct me, if there’s something better for this already in there.
=> color: Implement floating-point representation struct

color.d
- Additional documentation
- `opCast()`
- Offset functions
As discussed on Discord, this is the first (and most basic) PR of the presenter thing I’m currently working on.
This extends `Point` and `Size` in *color.d* with functionality that my own codebase had.
=> color: Extend point and size

simpledisplay.d
my use-case:
```d
struct MouseState
{
bool dragging;
int dragStartX, dragStartY;
int dragModifierState;
bool qualifiesClick;
}
MouseState[16] mouseButtonStates;
void handleMouseEvent(MouseEvent e)
{
import std.math : abs, round;
if (e.type == MouseEventType.motion)
{
foreach (btn, ref state; mouseButtonStates)
{
if (state.qualifiesClick && abs(e.x - state.dragStartX) + abs(e.y - state.dragStartY) > 8)
state.qualifiesClick = false;
else if (state.dragging && (btn == MouseButtonLinear.middle
|| ((state.dragModifierState & ModifierState.alt) != 0
&& (btn == MouseButtonLinear.left || btn == MouseButtonLinear.right))))
{
viewOffsetX += e.dx;
viewOffsetY += e.dy;
}
}
}
...
```
=> add MouseButtonLinear to sdpy

pixmappresenter.d
Noticed that this ctor was missing.
It’s just a convenience feature but I think it’s useful enough. My original codebase had it. (Currently porting it to use PixmapPresenter.)
=> Add ctor for making Pixmaps from user-provided slice

nanovega.d
this is both needed for modern opengl because if you are unlucky with your graphics drivers there it won't render anything when the core context is enabled, but also when rendering custom data and having stray VAOs open that you didn't unbind on the start of the nanovega render calls.
stuff like `glEnableVertexAttribArray` and `glVertexAttribPointer`, which is called below, is only valid with a VAO bound, which wasn't the case before and was just lucky that it worked at all.
=> fix nanovega tainting the active VAO

email.d
Some small patches for better RFC 2045 conformance. The behaviour introduced is equivalent to what thunderbird would produce, thus should not break anything (unless thunderbird has some special handling for weird public mailservers, in which case all of this hopeless anyways)
=> Rfc2045 fixes

email.d
Untested POC. I'll probably get around to create some tests for this on the weekend.
=> Remove an allocation when decoding base64

com.d
I just noticed that an enum for VARIANT.vt is already in druntime.
=> Use VARENUM instead of own enum

color.d
In its current form, this is a breaking change suitable for arsd 12 or a later major release.
`Color.components` is turned into `ubyte[4]`.
Unlike an anonymous union, this works with CTFE as well.
`r`, `g`, `b`, `a` and `asUint` are turned into getter + setter functions.
A sufficiently good optimizing compiler will generate the same code for these as it would previously have with the union. (Note that this cannot be confirmed with DMD’s built-in profiler as it’s implementation will poison any getter/setter functions.)
The *alias this* stems from my codebase which did use it to simplify certain implementation details.
I’m not sure whether it’s a good thing or even worth it.
```d
/+ code sample +/
foreach (immutable idx, ref component; pixelDestination) {}
/+ vs +/
foreach (immutable idx, …
```
=> color: Replace color components union with property functions

com.d
Allows you to do this with the Excel COM interface:
```
auto range = sheet.Range()(sheet.Cells()(1, 1), sheet.Cells()(3, 4));
```
=> Allow converting ComResult to VARIANT

com.d
Not sure how close to finished the `ComObjectImpl` and `IDispatchImpl` mixins are, but this at least helps getting rid of a compile error.
=> com.d: Fix EXCEPINFO.scode capitalization

com.d
When Excel calls back into my application through `IDispatch.Invoke` from an object I passed through `Advise`, it hangs and eventually a pop up shows "Microsoft Excel is waiting for another application to complete an OLE action". Turns out I need to use `COINIT_MULTITHREADED`. This adds an option for it while remaining backwards compatible with the COINIT_APARTMENTTHREADED default.
=> com.d: Add option for multithreaded COM

com.d
Allows you to do:
```D
CommandBars()("Cell").Controls().Add().callNamedArgs!(["Type", "Temporary"])(10, true);
```
('Temporary' is argument 4 and I don't know what the intermediate arguments are lol)
Would be cool to add named argument support to `opCall`, I might write an enhancement / DIP for that. Then it could just be:
```D
Controls().Add()(Type: 10, Temporary: true);
```
=> com.d: Add named argument support

com.d
- Fix `long` to set `llVal` (`hVal` doesn't exist)
- Use VARENUM instead of magic constants
- Add case for a plain `IDispatch` class instance
=> com.d: Fix/improve toComVariant

postgres.d
Dependency was throwing error 
`
template instance `arsd.postgres.PostgreSql.executePreparedStatement!(char, char)` error instantiating `
when  use executePreparedStatement
DUB : 1.38.1
PostgreSQL: 16
I got this error in the package 
`
template 'to' is not callable using argument types '!(string)(char)'`
where the usage is ` db.executePreparedStatement("update_tbl_cmd",'3','a');`
=> Fix for error at string to char* conversion in `executePreparedStatement` in Postgres.d

pixmaprecorder.d
- Improved documentation.
- Contains an important bugfix (2f32267898d78ce5a8ef7c2b064fc8f943915d62).
- Contains a kinda important documentation fix (https://github.com/adamdruppe/arsd/commit/f432e7d744e47f22674ddf999921c542521aa456#diff-a456ad4100179e76b7737d40226e9e8f90fb1178371522f3bb46a65ba13caa04R128).
- Additional aliases providing further “less technical” method names.
- Allows the recorder to process `const` pixmaps.
=> Pixmap Recorder revision Ⅰ

pixmappaint.d
I’m not sure whether leaving it undocumented was on purpose.
Also it left out the “tech preview” warning from the generated documentation.
I’d say, let’s document it :grin:
=> Document Pixmap Paint module

core.d
There's a compile error when using `-preview=dip1000`:
```D
static SocketAddress[] localhost(ushort port, return UserProvidedBuffer!SocketAddress buffer = null) {
buffer.append(ip6("::1", port));
buffer.append(ip4("127.0.0.1", port));
return buffer.slice;
}
```
```
C:\Users\Dennis\AppData\Local\dub\packages\arsd-official\11.4.2\arsd-official\core.d(3066,10): Error: returning `buffer.slice()` escapes a reference to parameter `buffer`
C:\Users\Dennis\AppData\Local\dub\packages\arsd-official\11.4.2\arsd-official\core.d(3181,10): Error: returning `buffer.slice()` escapes a reference to parameter `buffer`
```
The `UserProvidedBuffer.slice` method is annotated `return (ref)` but it should be `return scope`, or since it's a template, just inferred.
=> core.d: Fix wrong `return` annotation on UserProvidedBuffer.slice

dub.json, pixmappresenter.d, simpledisplay.d
As discussed on Discord, here’s my PR to add this feature.
This reclaims the pixels otherwise lost to rounded window corners.
Tested on Windows 11 + Windows 10 (where it does nothing due to the lack of support for the underlying feature, but does not crash either).
For convenience reasons we currently provide a dummy for unsupported systems that stores the value in a field without further processing. (This is also used as a fallback on unsupported Windows versions.)
In my tests (cross-linking on Linux!) it also works without explicitly passing `dwmapi` to the linker.
Not sure about Windows and the MS linker though. I think we should keep it – even if it’s just for cleanness purposes.
In general, I’d appreciate if someone developing on Windows could give this a try; thanks!
<details> …
=> Implement "corner style" property for sdpy windows on Windows 11+

core.d, pixmappresenter.d
Recent changes introduced a symbol conflict that broke PixmapPresenter.
=> Timer conflict

simpledisplay.d
- Use tabs for indentation consistently.
- Use spaces for alignment. (Some of those would use a tab for the first 8 spaces of alignment.)  
(There’s still a number of alignment issues left in the GL bindings afaict.)
Not much advantage of using tabs, when they make havoc with alignment.
=> Fix tabs/space mixing in sdpy

postgres.d
Skip the slow std.uni.toLower call unless it's necessary.
Flagged this with a profiler - this is not a very nice patch but it does give a 15% speed-up for a DB import script I'm working on. What do you think?
=> [RFC] arsd.postgres: Add fast path for field name conversion

terminal.d
Druntime is missing the tcgetattr/tcsetattr binding for musl. Here we add them to allow building on musl.
=> feat(terminal): Add bindings to support musl

terminal.d
I am an idiot. I got the compiles import syntax wrong and missed the extern C.
Now tested it with actual musl environment, so this should be fine.
=> fix(terminal): fix conditional binding for musl

cgi.d
`HEAD` requests are not supposed to have a body.
MDN suggests that…
> If a response to a HEAD request has a body, the response body must be ignored.
Web browser seem to handle such situations well.
Unfortunately, Node.js does not; instead it tries to parse the empty chunk as a new HTTP response and reports an error.
(Code `HPE_INVALID_CONSTANT` with reason "Expected HTTP/")
=> Do not send empty chunk for HEAD requests
